services:
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - clapbackbot-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
      args:
        API_KEY: ${API_KEY}
    environment:
      - API_KEY=${API_KEY}
      - BACKEND_MODE=${BACKEND_MODE}
    ports:
      - "5000:5000"
    networks:
      - clapbackbot-network
    
networks:
  clapbackbot-network:
    driver: bridge