FROM python:3.12-slim

WORKDIR /app 
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

ARG API_KEY
RUN test -n "$API_KEY" || (echo "ERROR: missing build argument API_KEY" && exit 1)

EXPOSE 5000
CMD ["python3", "server.py"]

